### ISSUE TITLE
question about agent

### ISSUE THREAD

**Issue by liuyangc3** [convox-examples/dd-agent#12]
hi @ddollar , I notice there is `agent` config under a service 
```
services:
  my_app:
    agent:
      ports:
        - 8125/udp
        - 8126/tcp
```
what does this agent mean ? why not just use ports like this
```
services:
  my_app:
    ports:
      - 8125/udp
      - 8126/tcp
```
